# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPruebalogin(unittest.TestCase):
  def setUp(self):
     self.driver = webdriver.Firefox()
  
 
  
  def test_pruebalogin(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(550, 693)
    self.driver.find_element(By.ID, "id_username").send_keys("jeselirod")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Se180uS748ii")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def teardown_method(self, method):
     self.driver.quit()

if __name__ == '__main__':
    unittest.main()
  
